FROM node:22.14.0-bookworm-slim

# set working directory
WORKDIR /app

# copy package.json and package-lock.json
COPY package*.json ./

# install app dependencies
RUN npm ci --omit=dev

# copy app source code
COPY . .

# final configuration
EXPOSE 5000
CMD ["npm", "start"]