FROM node:22-bookworm

# set working directory
WORKDIR /app

# copy package.json and package-lock.json
COPY package*.json ./

# install app dependencies
RUN npm install 

# copy app source code
COPY . .

# final configuration
EXPOSE 5000
CMD ["npm", "run", "dev"]
